config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#index'

  get '/sign_in', to: 'authentication#login'
  get '/sign_up', to: 'authentication#registration'

  post '/sign_in', to: 'authentication#process_login'
  post '/sign_up', to: 'authentication#process_registration'

  get '/sign_out', to: 'authentication#logout', as: 'logout'

  get '/verification/new', to: 'authentication#new_verification_email', as: 'new_verification'
  post '/verification/new', to: 'authentication#process_new_verification_email'

  get '/verification/:code', to: 'authentication#verify_email', as: 'verification'

  get '/reset_password', to: 'authentication#new_password_reset_request'
  post '/reset_password', to: 'authentication#process_password_reset_request'

  get '/reset_password/:code', to: 'authentication#process_password_reset', as: 'password_reset'

  get '/users/ban/:id', to: 'users#ban', as: 'ban'
  get '/users/unban/:id', to: 'users#unban', as: 'unban'

  get '/discord/', to: 'discord#index', as: 'discord'
  get '/discord/verification', to: 'discord#show_code', as: 'discord_verification'

  scope '/api' do
    post '/discord/complete_verification/:code/:discord_id',
         to: 'discord#complete',
         as: 'complete_discord_verification',
         format: :json

    get '/discord/check_verification/:discord_id',
        to: 'discord#check',
        as: 'check_discord_verification',
        format: :json
  end

  resources :testers
  resources :users

  scope '/admin' do
    resources :api_tokens, only: %i[index new destroy]
    resources :subjects, except: %i[show]
    resources :discord_servers, except: %i[show]
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password

  has_one :email_verification
  has_one :discord_verification

  has_many :testers

  extend Blacklist

  validates :username, presence: true,
                       format: { with: /\A[0-9a-z]+\z/ },
                       exclusion: { in: blacklist }

  validate :unique_username

  def display_name
    name.empty? ? username.truncate(16) : name
  end

  def avatar_url
    "https://avatars.dicebear.com/4.5/api/avataaars/#{username + avatar_discriminator}.svg"
  end

  def unique_username
    User.where(username: username)
        .or(User.where(username: Digest::RMD160.hexdigest(username)))
        .none?
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate!
  before_action :set_user, except: [:index]

  def index
    authorize! :read, :users

    @users = User.order(is_admin: :desc, is_verified: :desc).all
  end

  def ban
    authorize! :ban, @user

    return redirect_to user_url(@user), alert: 'Nelze zabanovat administrátora.' if @user.is_admin

    @user.update is_banned: true
    redirect_to user_url(@user), notice: "Uživatel #{@user.display_name} byl zabanován."
  end

  def unban
    authorize! :unban, @user

    @user.update is_banned: false
    redirect_to user_url(@user), notice: "Uživatel #{@user.display_name} byl odbanován."
  end

  def destroy
    authorize! :destroy, @user

    return redirect_to user_url(@user), alert: 'Nelze smazat účet administrátora.' if @user.is_admin

    @user.delete
    redirect_to users_url, notice: "Uživatel #{@user.display_name} byl smazán."
  end

  def show
    authorize! :view, @user
  end

  def edit
    authorize! :manage, @user
  end

  def update
    authorize! :manage, @user

    @user.update user_params

    redirect_to user_url(@user), notice: 'Změny byly uloženy.'
  end

  private

  def set_user
    @user = User.find params[:id]
  end

  def user_params
    params.require(:user).permit(:name, :avatar_discriminator, :password)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/edit.html.erb
<%= form_with(model: @user, url: user_url(@user), method: :patch) do %>
  <div class="ui stackable grid">
    <div class="ui five wide column">
      <h1>Upravit účet</h1>
      <div class="ui card">
        <div class="image">
          <div class="ui inverted dimmer" id="avatar-dimmer">
            <div class="ui loader"></div>
          </div>
          <img src="<%= @user.avatar_url %>" id="avatar"
               data-template="<%= @user.avatar_url.gsub(@user.avatar_discriminator + ".svg", "DISCRIMINATOR.svg") %>">
        </div>
        <div class="content ui form">
          <%= hidden_field :user, :avatar_discriminator, id: 'avatar_discriminator' %>
          <div class="ui labeled icon button fluid" id="random-avatar-button">
            <i class="dice icon"></i>
            Náhodný avatar
          </div>
        </div>
        <div class="content ui form">
          <div class="field">
            <%= label_tag "Jméno a příjmení" %>
            <%= text_field :user, :name, placeholder: 'Nepovinné' %>
          </div>
          <div class="meta">
            <small class="hash"><%= @user.username %></small>
          </div>
        </div>
        <div class="extra content">
          <%= submit_tag "Uložit změny", class: 'ui fluid button primary' %>
        </div>
      </div>
    </div>

    <% if @user.id == current_user.id %>
      <div class="eight wide column">
        <h1>Změna hesla</h1>

        <div class="ui segment">
          <div class="ui form">
            <div class="field">
              <%= label_tag :password, "Nové heslo" %>
              <div class="input">
                <%= password_field :user, :password, minlength: 8 %>
              </div>
              <small>Minimálně 8 znaků</small>
            </div>
            <%= submit_tag "Nastavit nové heslo", class: 'ui button primary' %>
          </div>
        </div>
      </div>
    <% end %>

    <script>
        $(function () {
            const image = $("#avatar");
            const dimmer = $("#avatar-dimmer");
            const input = $("#avatar_discriminator");

            $("#random-avatar-button").click(function () {
                const discriminator = (Math.random().toString(36) + Math.random().toString(36)).replace(/\./g, "");

                dimmer.addClass("active");

                image.attr("src", image.data("template").replace("DISCRIMINATOR", discriminator));
                input.val(discriminator);

                image.on("load", () => dimmer.removeClass("active"));
            });
        });
    </script>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>Správa uživatelů</h1>
<p>Celkem registrováno <%= @users.count %> uživatelů</p>

<hr>

<table class="ui celled table">
  <thead>
  <tr>
    <th>ID</th>
    <th>Avatar</th>
    <th>Školní xname / hash</th>
    <th>Jméno</th>
    <th>Aktivní účet?</th>
    <th>Admin?</th>
    <th>Ban?</th>
    <th>Akce</th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr
    <% if user.is_admin %> class="red"
    <% end %>>
      <td><%= user.id %></td>
      <td><img src="<%= user.avatar_url %>" class="ui mini avatar image"></td>
      <td><b><%= user.username %></b></td>
      <td><%= user.name.presence || "-" %></td>
      <td><i class="<%= user.is_verified ? "check" : "times" %> icon"></i></td>
      <td><i class="<%= user.is_admin ? "check" : "times" %> icon"></i></td>
      <td><i class="<%= user.is_banned ? "check" : "times" %> icon"></i></td>
      <td>
        <%= link_to 'Zobrazit', user_url(user), class: 'ui secondary button' %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<div class="ui stackable grid">
  <div class="five wide column">
    <div class="ui card">
      <div class="image">
        <img src="<%= @user.avatar_url %>">
      </div>
      <div class="content">
        <a class="header"><%= @user.name.presence || "Anonymní účet" %></a>
        <% if @user.is_admin %>
          <div>Administrátor</div>
        <% elsif @user.is_banned %>
          <div>Banovaný uživatel</div>
        <% elsif @user.is_verified %>
          <div>Aktivovaný účet</div>
        <% else %>
          <div>Účet čeká na aktivaci</div>
        <% end %>
        <div class="meta">
          <small class="hash"><%= @user.username %></small>
        </div>
      </div>
      <% if can? :ban, @user %>
        <div class="content">
          <% if @user.is_banned %>
            <%= link_to "Odblokovat účet", unban_url(@user), class: "ui secondary button", data: { confirm: "Opravdu odbanovat uživatele #{@user.display_name}?" } %>
          <% else %>
            <%= link_to "Blokovat účet", ban_url(@user), class: "ui secondary button", data: { confirm: "Opravdu zabanovat uživatele #{@user.display_name}?" } %>
          <% end %>

          <%= link_to "Smazat účet", user_url(@user), class: "ui button red", data: { confirm: "Opravdu smazat uživatele #{@user.display_name}? Tato akce je nevratná." }, method: :delete %>
        </div>
      <% end %>
      <div class="extra content">
        <%= link_to "Upravit účet", edit_user_url(@user), class: 'ui fluid button primary' %>
      </div>
    </div>

  </div>
  <div class="ten wide column">
    <div class="ui placeholder basic segment">
      <div class="ui icon grey header">
        <i class="history icon"></i>
        Tady bude historie nebo nedávná aktivita
      </div>
    </div>
  </div>
</div>