config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#index'

  get '/sign_in', to: 'authentication#login'
  get '/sign_up', to: 'authentication#registration'

  post '/sign_in', to: 'authentication#process_login'
  post '/sign_up', to: 'authentication#process_registration'

  get '/sign_out', to: 'authentication#logout', as: 'logout'

  get '/verification/new', to: 'authentication#new_verification_email', as: 'new_verification'
  post '/verification/new', to: 'authentication#process_new_verification_email'

  get '/verification/:code', to: 'authentication#verify_email', as: 'verification'

  get '/reset_password', to: 'authentication#new_password_reset_request'
  post '/reset_password', to: 'authentication#process_password_reset_request'

  get '/reset_password/:code', to: 'authentication#process_password_reset', as: 'password_reset'

  get '/users/ban/:id', to: 'users#ban', as: 'ban'
  get '/users/unban/:id', to: 'users#unban', as: 'unban'

  get '/discord/', to: 'discord#index', as: 'discord'
  get '/discord/verification', to: 'discord#show_code', as: 'discord_verification'

  scope '/api' do
    post '/discord/complete_verification/:code/:discord_id',
         to: 'discord#complete',
         as: 'complete_discord_verification',
         format: :json

    get '/discord/check_verification/:discord_id',
        to: 'discord#check',
        as: 'check_discord_verification',
        format: :json
  end

  resources :testers
  resources :users

  scope '/admin' do
    resources :api_tokens, only: %i[index new destroy]
    resources :subjects, except: %i[show]
    resources :discord_servers, except: %i[show]
  end
end

app/models/discord_server.rb
# frozen_string_literal: true

class DiscordServer < ApplicationRecord
  validates :priority, numericality: { greater_than: 0 }
  validates :embed_url, :invite_url, :priority, presence: true
  validates_uniqueness_of :embed_url, :invite_url, scope: :id
end

app/controllers/discord_servers_controller.rb
# frozen_string_literal: true

class DiscordServersController < ApplicationController
  before_action :set_discord_server, only: %i[show edit update destroy]
  before_action :require_admin_privileges!

  # GET /discord_servers
  # GET /discord_servers.json
  def index
    @discord_servers = DiscordServer.order(priority: :desc).all
  end

  # GET /discord_servers/new
  def new
    @discord_server = DiscordServer.new
  end

  # GET /discord_servers/1/edit
  def edit; end

  # POST /discord_servers
  # POST /discord_servers.json
  def create
    @discord_server = DiscordServer.new(discord_server_params)

    respond_to do |format|
      if @discord_server.save
        format.html { redirect_to discord_servers_url, notice: 'Discord server was successfully created.' }
        format.json { render :show, status: :created, location: @discord_server }
      else
        format.html { render :new }
        format.json { render json: @discord_server.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discord_servers/1
  # PATCH/PUT /discord_servers/1.json
  def update
    respond_to do |format|
      if @discord_server.update(discord_server_params)
        format.html { redirect_to discord_servers_url, notice: 'Discord server was successfully updated.' }
        format.json { render :show, status: :ok, location: @discord_server }
      else
        format.html { render :edit }
        format.json { render json: @discord_server.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discord_servers/1
  # DELETE /discord_servers/1.json
  def destroy
    @discord_server.destroy
    respond_to do |format|
      format.html { redirect_to discord_servers_url, notice: 'Discord server was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_discord_server
    @discord_server = DiscordServer.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def discord_server_params
    params.require(:discord_server).permit(:embed_url, :invite_url, :priority)
  end
end

app/helpers/discord_servers_helper.rb
# frozen_string_literal: true

module DiscordServersHelper
end

app/views/discord_servers/_form.html.erb
<div class="ui segment">
  <div class="content">
    <div class="ui form">
      <%= form_with(model: discord_server) do |form| %>
        <% if discord_server.errors.any? %>
          <div id="error_explanation">
            <b><%= pluralize(discord_server.errors.count, "error") %> prohibited this Discord server from being
              saved:</b>

            <ul>
              <% discord_server.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field">
          <%= form.label :embed_url %>
          <div class="ui input">
            <%= form.text_field :embed_url %>
          </div>
        </div>

        <div class="field">
          <%= form.label :invite_url %>
          <div class="ui input">
            <%= form.text_field :invite_url %>
          </div>
        </div>

        <div class="field">
          <%= form.label :priority %>
          <div class="ui input">
            <%= form.number_field :priority %>
          </div>
        </div>

        <div class="actions mt-3 form-group">
          <%= form.submit 'Uložit', class: "ui button primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/discord_servers/edit.html.erb
<h1>Upravit Discord server</h1>

<%= render 'form', discord_server: @discord_server %>

app/views/discord_servers/index.html.erb
<h1>Discord servery</h1>

<div>
  <%= link_to 'Přidat Discord server', new_discord_server_path, class: 'ui green button' %>
</div>

<br>

<div class="ui cards">
  <% @discord_servers.each do |discord_server| %>
    <div class="ui card">
      <div class="image">
        <%= image_tag discord_server.embed_url %>
      </div>
      <div class="content">
        <p>
          <strong>Invite url</strong><br>
          <%= link_to discord_server.invite_url, discord_server.invite_url, target: '_blank' %>
        </p>

        <p>
          <strong>Priority:</strong>
          <%= discord_server.priority %>
        </p>
      </div>
      <div class="content">
        <%= link_to 'Upravit', edit_discord_server_path(discord_server), class: 'ui primary button' %>
        <%= link_to 'Smazat', discord_server, method: :delete, class: 'ui red button', data: { confirm: 'Are you sure?' } %>
      </div>
    </div>
  <% end %>
</div>

app/views/discord_servers/new.html.erb
<h1>Přidat Discord server</h1>

<%= render 'form', discord_server: @discord_server %>