config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#index'

  get '/sign_in', to: 'authentication#login'
  get '/sign_up', to: 'authentication#registration'

  post '/sign_in', to: 'authentication#process_login'
  post '/sign_up', to: 'authentication#process_registration'

  get '/sign_out', to: 'authentication#logout', as: 'logout'

  get '/verification/new', to: 'authentication#new_verification_email', as: 'new_verification'
  post '/verification/new', to: 'authentication#process_new_verification_email'

  get '/verification/:code', to: 'authentication#verify_email', as: 'verification'

  get '/reset_password', to: 'authentication#new_password_reset_request'
  post '/reset_password', to: 'authentication#process_password_reset_request'

  get '/reset_password/:code', to: 'authentication#process_password_reset', as: 'password_reset'

  get '/users/ban/:id', to: 'users#ban', as: 'ban'
  get '/users/unban/:id', to: 'users#unban', as: 'unban'

  get '/discord/', to: 'discord#index', as: 'discord'
  get '/discord/verification', to: 'discord#show_code', as: 'discord_verification'

  scope '/api' do
    post '/discord/complete_verification/:code/:discord_id',
         to: 'discord#complete',
         as: 'complete_discord_verification',
         format: :json

    get '/discord/check_verification/:discord_id',
        to: 'discord#check',
        as: 'check_discord_verification',
        format: :json
  end

  resources :testers
  resources :users

  scope '/admin' do
    resources :api_tokens, only: %i[index new destroy]
    resources :subjects, except: %i[show]
    resources :discord_servers, except: %i[show]
  end
end

app/models/subject.rb
# frozen_string_literal: true

class Subject < ApplicationRecord
  has_many :testers

  validates_presence_of :name, :code
  validates_uniqueness_of :code, scope: :id
end

app/controllers/subjects_controller.rb
# frozen_string_literal: true

class SubjectsController < ApplicationController
  before_action :set_subject, only: %i[show edit update destroy]
  before_action :require_admin_privileges!

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show; end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit; end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to subjects_url, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to subjects_url, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_subject
    @subject = Subject.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def subject_params
    params.require(:subject).permit(:code, :name)
  end
end

app/helpers/subjects_helper.rb
# frozen_string_literal: true

module SubjectsHelper
end

app/views/subjects/_form.html.erb
<div class="ui segment">
  <div class="content">
    <div class="ui form">
      <%= form_with(model: subject) do |form| %>
        <div class="ui form">
          <% if subject.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

              <ul>
                <% subject.errors.each do |error| %>
                  <li><%= error.full_message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="field">
            <%= form.label :code, 'Kód předmětu'  %>
            <div class="ui input">
              <%= form.text_field :code, placeholder: 'např. 4IZ110' %>
            </div>
          </div>

          <div class="field">
            <%= form.label :name, 'Název' %>
            <div class="ui input">
              <%= form.text_field :name %>
            </div>
          </div>

          <div class="actions form-group mt-3">
            <%= form.submit class: 'ui primary button' %>
          </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/subjects/edit.html.erb
<h1>Upravit předmět</h1>

<%= render 'form', subject: @subject %>

app/views/subjects/index.html.erb
<h1>Předměty</h1>

<div>
  <%= link_to 'Přidat předmět', new_subject_path, class: 'ui green button' %>
</div>

<table class="ui celled table">
  <thead>
  <tr>
    <th>Kód předmětu</th>
    <th>Název</th>
    <th>Akce</th>
  </tr>
  </thead>

  <tbody>
  <% @subjects.each do |subject| %>
    <tr>
      <td><%= subject.code %></td>
      <td><%= subject.name %></td>
      <td>
        <%= link_to 'Upravit', edit_subject_path(subject), class: 'ui button' %>
        <%= link_to 'Smazat', subject, method: :delete, data: { confirm: 'Are you sure?' }, class: 'ui red button' %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/subjects/new.html.erb
<h1>Přidat předmět</h1>

<%= render 'form', subject: @subject %>