config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#index'

  get '/sign_in', to: 'authentication#login'
  get '/sign_up', to: 'authentication#registration'

  post '/sign_in', to: 'authentication#process_login'
  post '/sign_up', to: 'authentication#process_registration'

  get '/sign_out', to: 'authentication#logout', as: 'logout'

  get '/verification/new', to: 'authentication#new_verification_email', as: 'new_verification'
  post '/verification/new', to: 'authentication#process_new_verification_email'

  get '/verification/:code', to: 'authentication#verify_email', as: 'verification'

  get '/reset_password', to: 'authentication#new_password_reset_request'
  post '/reset_password', to: 'authentication#process_password_reset_request'

  get '/reset_password/:code', to: 'authentication#process_password_reset', as: 'password_reset'

  get '/users/ban/:id', to: 'users#ban', as: 'ban'
  get '/users/unban/:id', to: 'users#unban', as: 'unban'

  get '/discord/', to: 'discord#index', as: 'discord'
  get '/discord/verification', to: 'discord#show_code', as: 'discord_verification'

  scope '/api' do
    post '/discord/complete_verification/:code/:discord_id',
         to: 'discord#complete',
         as: 'complete_discord_verification',
         format: :json

    get '/discord/check_verification/:discord_id',
        to: 'discord#check',
        as: 'check_discord_verification',
        format: :json
  end

  resources :testers
  resources :users

  scope '/admin' do
    resources :api_tokens, only: %i[index new destroy]
    resources :subjects, except: %i[show]
    resources :discord_servers, except: %i[show]
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Guests have no rights
    return unless user.present?

    # Grant all privileges to administrators
    if user.is_admin
      can :manage, :all
      can :manage, User
      return
    end
    
    # Everybody can view public testers
    can :view, Tester, is_public: true
    
    # Owners (and admins) can view and manage their testers
    can :manage, Tester, user_id: user.id

    # Users can manage their own user profile
    can :manage, User, id: user.id

    # But cannot ban, unban or delete it
    cannot %i[ban unban destroy], User
  end
end

app/models/api_token.rb
# frozen_string_literal: true

class ApiToken < ApplicationRecord
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/discord_server.rb
# frozen_string_literal: true

class DiscordServer < ApplicationRecord
  validates :priority, numericality: { greater_than: 0 }
  validates :embed_url, :invite_url, :priority, presence: true
  validates_uniqueness_of :embed_url, :invite_url, scope: :id
end

app/models/discord_verification.rb
# frozen_string_literal: true

class DiscordVerification < ApplicationRecord
  belongs_to :user
end

app/models/email_verification.rb
# frozen_string_literal: true

class EmailVerification < ApplicationRecord
  belongs_to :user
  validates_presence_of :user
end

app/models/subject.rb
# frozen_string_literal: true

class Subject < ApplicationRecord
  has_many :testers

  validates_presence_of :name, :code
  validates_uniqueness_of :code, scope: :id
end

app/models/tester.rb
class Tester < ApplicationRecord
  belongs_to :user
  belongs_to :subject

  validates_presence_of :subject_id, :user_id, :questions, :is_public
  validates :questions, json: { schema: "#{Rails.root}/app/models/schemas/tester_questions.json" }

  scope :visible_by, -> (user) { Tester.where(user_id: user.id).or(Tester.where(is_public: true)) }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password

  has_one :email_verification
  has_one :discord_verification

  has_many :testers

  extend Blacklist

  validates :username, presence: true,
                       format: { with: /\A[0-9a-z]+\z/ },
                       exclusion: { in: blacklist }

  validate :unique_username

  def display_name
    name.empty? ? username.truncate(16) : name
  end

  def avatar_url
    "https://avatars.dicebear.com/4.5/api/avataaars/#{username + avatar_discriminator}.svg"
  end

  def unique_username
    User.where(username: username)
        .or(User.where(username: Digest::RMD160.hexdigest(username)))
        .none?
  end
end

app/models/user_verification.rb
# frozen_string_literal: true

class UserVerification < ApplicationRecord
  belongs_to :user
  validates_presence_of :user
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate!
  before_action :set_user, except: [:index]

  def index
    authorize! :read, :users

    @users = User.order(is_admin: :desc, is_verified: :desc).all
  end

  def ban
    authorize! :ban, @user

    return redirect_to user_url(@user), alert: 'Nelze zabanovat administrátora.' if @user.is_admin

    @user.update is_banned: true
    redirect_to user_url(@user), notice: "Uživatel #{@user.display_name} byl zabanován."
  end

  def unban
    authorize! :unban, @user

    @user.update is_banned: false
    redirect_to user_url(@user), notice: "Uživatel #{@user.display_name} byl odbanován."
  end

  def destroy
    authorize! :destroy, @user

    return redirect_to user_url(@user), alert: 'Nelze smazat účet administrátora.' if @user.is_admin

    @user.delete
    redirect_to users_url, notice: "Uživatel #{@user.display_name} byl smazán."
  end

  def show
    authorize! :view, @user
  end

  def edit
    authorize! :manage, @user
  end

  def update
    authorize! :manage, @user

    @user.update user_params

    redirect_to user_url(@user), notice: 'Změny byly uloženy.'
  end

  private

  def set_user
    @user = User.find params[:id]
  end

  def user_params
    params.require(:user).permit(:name, :avatar_discriminator, :password)
  end
end

app/helpers/api_tokens_helper.rb
# frozen_string_literal: true

module ApiTokensHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/authentication_helper.rb
# frozen_string_literal: true

module AuthenticationHelper
end

app/helpers/discord_helper.rb
# frozen_string_literal: true

module DiscordHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/subjects_helper.rb
# frozen_string_literal: true

module SubjectsHelper
end

app/helpers/testers_helper.rb
module TestersHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Studentský portál FIS VŠE</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/fomantic-ui@2.8.7/dist/semantic.min.css">

  <script src="https://cdn.jsdelivr.net/npm/jquery@3.3.1/dist/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/fomantic-ui@2.8.7/dist/semantic.min.js"></script>
</head>

<body style="min-height: 100vh; display: flex; flex-flow: column nowrap;">
<header class="ui inverted relaxed segment">
  <div class="ui container">
    <h1 class="ui inverted huge text">Studentský portál</h1>
    <div class="ui huge text">Komunitní server pro studenty FIS VŠE v Praze</div>

    <div class="ui inverted secondary pointing menu">
      <%= link_to "Domovská stránka", root_url, class: 'active item' %>
      <% if authenticated? %>
        <div class="ui dropdown item">
          <i class="student icon"></i>
          Studovna
          <i class="dropdown icon"></i>
          <div class="menu">
            <%= link_to testers_url, class: 'item' do %>
              <i class="check icon"></i> Testery
            <% end %>
            <a href="/test_results" class="item" id="rickroll-trigger">
              <i class="star icon"></i> Výsledky testů a leaknuté zkouškové otázky
            </a>
            <div class="ui basic modal" id="rickroll">
              <div class="content">
                <iframe width="1080" height="720" data-src="https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
              </div>
            </div>
            <script>
              $(function () {
                  $("#rickroll-trigger").click(function (event) {
                      event.preventDefault();
                      const video = $("#rickroll iframe").first();

                      // Automatically play the video on modal trigger
                      video.attr("src", video.data("src"));
                      $("#rickroll").modal("show");
                  })
              })
            </script>
          </div>
        </div>
        <%= link_to discord_url, class: 'item' do %><i class="discord icon"></i> Discord<% end %>
      <% end %>

      <div class="right menu">
        <% if authenticated? %>
          <% if current_user.is_admin %>
            <div class="ui dropdown item">
              <i class="wrench icon"></i>
              Administrace
              <i class="dropdown icon"></i>
              <div class="menu">
                <a class="item" href="<%= users_url %>"><i class="users icon"></i> Správa uživatelů</a>
                <a class="item" href="<%= api_tokens_url %>"><i class="key icon"></i> Správa API tokenů</a>
                <a class="item" href="<%= discord_servers_url %>"><i class="discord icon"></i> Správa Discord
                  serverů</a>
                <a class="item" href="<%= subjects_url %>"><i class="tags icon"></i> Správa předmětů</a>
              </div>
            </div>
          <% end %>
          <a href="<%= user_url(current_user) %>" class="item">
            <i class="<%= current_user.is_admin ? "red shield" : "user" %> icon"></i>
            <%= current_user.display_name %>
          </a>
          <%= link_to logout_url, class: "item" do %>
            <i class="sign out icon"></i> Odhlásit se
          <% end %>
        <% else %>
          <%= link_to sign_in_url, class: "item" do %>
            <i class="sign in icon"></i> Přihlásit se
          <% end %>
          <%= link_to sign_up_url, class: "item ui text blue" do %>
            <i class="user plus icon"></i> Registrace
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</header>
<main class="ui wide container" style="flex-grow: 1;">
  <% unless flash[:alert].nil? %>
    <div class="ui error message">
      <% if flash[:alert].respond_to?(:each) %>
        <b>
          Během zpracování požadavku došlo k chybám
        </b>
        <ul class="list">
          <% flash[:alert].each do |alert| %>
            <li><%= alert %></li>
          <% end %>
        </ul>
      <% else %>
        <b>
          <%= flash[:alert] %>
        </b>
      <% end %>
    </div>
  <% end %>

  <% unless flash[:notice].nil? %>
    <div class="ui info message">
      <b>
        <%= flash[:notice] %>
      </b>
    </div>
  <% end %>

  <div class="container horizontally">
    <%= yield %>
  </div>
</main>

<footer class="ui secondary basic segment">
  <div class="ui container">
    <div class="ui secondary pointing above menu">
      <a href="https://github.com/jirkavrba/studentsky-portal-fis-vse" target="_blank" class="item">
        <i class="github icon"></i>
        Zdrojové kódy
      </a>
      <a href="https://github.com/jirkavrba/studentsky-portal-fis-vse/issues/new" target="_blank" class="item">
        <i class="bug icon"></i>
        Nahlásit chybu
      </a>
      <%# TODO: Add privacy policy %>
    </div>
    <b>&copy; Jiří Vrba, Richard Kraus 2021</b>
  </div>
</footer>
<script>
    $('.dropdown').dropdown();
</script>
</body>
</html>